export const GET_STUDENTS_START = "GET_STUDENTS_START";
export const GET_STUDENTS_SUCCEEDED = "GET_STUDENTS_SUCCEEDED";
export const GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE";

export const USER_LOGS_OUT = "USER_LOGS_OUT";
export const CHANGE_USER_NAME = "CHANGE_USER_NAME";
export const USER_SIGNS_IN_START = "USER_SIGNS_IN_START";
export const USER_SIGNS_IN_SUCCEEDED = "USER_SIGNS_IN_SUCCEEDED";
export const USER_SIGNS_IN_FAILURE = "USER_SIGNS_IN_FAILURE";
